---
language: ruby
services:
    - docker
branches:
    only:
        - master
env:
  global:
    - DEST_ID=core
    - NSVER=7
    - DOCKER_IMAGE=nethserver/makerpms:devtoolset${NSVER}
    - >
        EVARS="
        -e DEST_ID
        -e TRAVIS_BRANCH
        -e TRAVIS_BUILD_ID
        -e TRAVIS_PULL_REQUEST_BRANCH
        -e TRAVIS_PULL_REQUEST
        -e TRAVIS_REPO_SLUG
        -e TRAVIS_TAG
        -e NSVER
        -e ENDPOINTS_PACK
        -e YUM_ARGS
        -e COMMAND
        "

script: |
      set -e
      export COMMAND="scl enable devtoolset-9 -- makerpms"
      docker run -ti \
        --name makerpms ${EVARS} \
        --hostname "b${TRAVIS_BUILD_NUMBER}.nethserver.org" \
        --volume $PWD:/srv/makerpms/src:ro ${DOCKER_IMAGE} \
        makerpms-travis *.spec
      docker commit makerpms nethserver/build
      docker run -ti ${EVARS} \
        -e SECRET \
        -e SECRET_URL \
        -e AUTOBUILD_SECRET \
        -e AUTOBUILD_SECRET_URL \
        nethserver/build uploadrpms-travis
